# Check code formatting and style

name: 'code-formatting'

on: [push, pull_request]

jobs:
  build:

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout repo'
      uses: actions/checkout@v3

    - name: 'Set up Python 3.7'
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'
        cache: 'pip'

    - name: 'Install dependencies'
      run: pip install .[dev]

    - name: 'Lint with flake8'
      run: flake8

    - name: 'Format with black'
      run: black --check .

    - name: 'Print package versions'
      run: pip list
